# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TestDemo-desktop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestDemo-desktop

end

target 'TestDemo-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AIHelpSDK', '~> 2.1.1'
  # Pods for TestDemo-mobile

end
